# Generated by Django 4.0.3 on 2022-03-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
